name: Sync Credit Product definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    paths:
      - 'OpenAPI/credit-core/credit-product.yml'

jobs:  
  sync-credit-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./OpenAPI/credit-core/credit-product.yml --key=${{ secrets.CREDIT_README_API_KEY }} --id=${{ secrets.CREDIT_API_DEFINITION_ID }}